### ISSUE TITLE
Tarea - 1

### ISSUE THREAD

**Issue by domingomery** [domingomery/patrones#1]
**Objetivo:** Entender e implementar un sistema de reconocimiento de patrones basado en características geométricas.

**Enunciado:** Hacer un reconocedor automático que diferencie entra las letras 'S' y 'C' mayúsculas de cualquier tamaño de los fonts Times New Roman, Ariel y Courier. El input es una imagen binaria que contiene una 'S' o una 'C'. En la imagen binaria los pixeles del fondo tienen un 0, y los pixeles de la letra tienen un 1. Para probar el algoritmo diseñado usaremos 100 imágenes (50 con la letra 'S' y 50 con la letra 'C') de distinto tamaño y distintos fonts, el programa debe entregar como output un 1 si es 'S' o un 0 si es una 'C'. El índice de desempeño será el número de letras reconocidas correctamete. Para la tarea se requiere escribir un código en Matlab o Python que tenga la siguiente sintaxis:

Y = reconocedorSC(X)

donde X es una matriz que contiene la imagen binaria de una letra, e Y es la salida (1 si es 'S' o un 0 si es una 'C')

No se aceptará el uso de librerías de reconocimiento de patrones, ni de machine learning. Sólo está permitido el uso de librerías de procesamiento de imágenes. No está permitido el uso del comando regionprops de Matlab.

El conjunto de imágenes que usen para diseñar la solución deberá ser creado por ustedes mismos.

**Comment by baarratia** [comment]
Hola profe, una pregunta:

¿Las imágenes pueden contener letras que presenten algún tipo de rotación, o solo estarán en distintas posiciones y tamaños? 

Por ejemplo: 

Imagen que según yo si o si puede estar en el conjunto de prueba:
![b-CCourier2](https://user-images.githubusercontent.com/11417516/54556687-25d3b980-4998-11e9-9a90-460d3a63de4c.png)

vs. Imágen que no sé si es factible:
![Srot](https://user-images.githubusercontent.com/11417516/54556792-6cc1af00-4998-11e9-89e4-975283a8bfea.png)

Muchas gracias!

**Comment by domingomery** [comment]
Las letras pueden estar en cualquier parte de la imagen, no están rotadas y sólo hay una letra por imagen. Saludos. Domingo

**Comment by baarratia** [comment]
Perfecto, muchas gracias :)

**Comment by Taeval** [comment]
Las librerías NumPy, Pillow y Matplotlib de Python están permitidas?

**Comment by domingomery** [comment]
Sí se puede usar las librerías de Python NumPy, Pillow, PIL y Matplotlib. No está permitido usar librerías que extraigan características ni que hagan clasificación de ninguna especie.

**Comment by yoavnavon** [comment]
Se puede utilizar algún dataset externo para entrenar un modelo?

**Comment by domingomery** [comment]
se puede hacer uso de un dataset de imágenes externo o bien puedes hacerlo escribiendo letras en powepoint y hacerles un pantallazo... como quieras.

**Comment by fcorencoret** [comment]
Puedo usar openCV para calcular momentum, perimetro, bounding rectangle etc...?

**Comment by domingomery** [comment]
La regla general sigue siendo que no se puede usar librerías/comandos que
hagan extracción de características y clasificación, es decir, para OpenCV
se puede usar los comandos de procesamiento de imágenes (input imagen -
output imagen), los comandos de lectura de imágenes, los comandos de
visualización, pero no se puede usar los comandos como los que mencionas
que hacen extracción de características, ni los comandos que hagan algún
tipo de clasificación.

**Comment by jgespinosa10** [comment]
Profesor, no entiendo muy bien como es la imagen que se recibe como input, podría mandar un ejemplo?

**Comment by jfcampos1** [comment]
El fondo de la imagen puede ser siempre el mismo? o la idea es hacer estas letras con colores distinto de fondo?

**Comment by perojas3** [comment]
Bien, podria subir un ejemplo de las matrices?
Es para evitar el error leer las matrices volteadas.

**Comment by fgvenegas** [comment]
Tengo una duda, las imagenes binarias que nos daran vendran como matrices directamente o seran imagenes .jpg que tenemos que leer y convertir a matriz nosotros. Si es la primera opcion, las matrices vendran con alguna extension especifica? Y respecto a los labels vendran o podemos asumir cosas como que siempre  las 50 primeras seran 'S' y las 50 ultimas 'C'?

**Comment by domingomery** [comment]
He aclarado todas las últimas preguntas de @jgespinosa10 @jfcampos1 @perojas3 y @fgvenegas en el [enunciado de la tarea](http://dmery.ing.puc.cl/index.php/teaching/patrones/tareas/). Por favor volver a revisarlo.

**Comment by negutierrez** [comment]
Profesor, el informe puede ser creado utilizando Publish de Matlab?

**Comment by fgvenegas** [comment]
Muchas gracias @domingomery. Me quedan 2 dudas: 
* Para probarlo se hara mediante la linea de comandos o se manipulara directamente el codigo para usar el clasificador?
* Si mi clasificador se "entrena", se debe guardar y entregar entrenado o lo entrenaran al probarlo (lo que implica que deberia entregar mi set de entrenamiento tambien)?

Gracias

**Comment by domingomery** [comment]
El informe debe ser un PDF de una sola página (Times New Roman, Espacio Simple, Tamaño Carta), se puede hacer en Latex, Word, Publish de Matlab, etc., siempre y cuando cumpla con estas restricciones.

**Comment by domingomery** [comment]
Para probarlo se ejecutará un código que llame 100 veces a la función 'Y = reconocedorSC(X)’ que ustedes hayan diseñado… cada llamada a la función será con una letra distinta (50 veces una ’S’ y 50 veces una ‘C’).

**Comment by fgvenegas** [comment]
Muchas gracias. Y respecto a la segunda pregunta cómo puedo entregarlo para que al revisar no tengan que "entrenar" el modelo nuevamente?

**Comment by domingomery** [comment]
El clasificador que diseñes debe tener parámetros que has encontrado en la fase de entrenamiento… los parámetros que encontraste en esta fase debes guardarlos en algún archivo , tu función debe leer este archivo. Debes entregar la función y el archivo de parámetros. Otra alternativa, es que los parámetros estén escritos en el mismo código, así no necesitas el archivo adicional.

**Comment by fgvenegas** [comment]
Vale gracias!

**Comment by mesepulveda** [comment]
Profesor, podemos asumir que las imágenes vendrán sin ruido? Es válido que la función llame a un .mat para cargar matrices grandes?

**Comment by Taeval** [comment]
Las imágenes/arrays con los se prueben los algoritmos creados serán todos de las mismas dimensiones? Por ejemplo el array que usted subió es de 400x280.

**Comment by MortizDX** [comment]
Profesor, tengo 2 dudas chicas:
1. El ejemplo del enunciado es un archivo mat ¿eso será el tipo de input que se le dará al programa? (o sea, nunca será una imagen como tal?)
2. ¿Se puede usar la función `bwlabel`?

**Comment by domingomery** [comment]
Mauricio: 1) la entrada a tu programa es una imagen binaria alamacenada en la variable X... no es un archivo mat. 2) bwlabel es de procesamiento de imágenes y sí se puede usar. Saludos

**Comment by domingomery** [comment]
sí, vienen libre de ruido... Saludos

**Comment by domingomery** [comment]
por favor leer bien el enunciado y las otras preguntas y respuestas antes de formular una nueva pregunta... gracias!

**Comment by Mnfriedl** [comment]
Profesor, en el informe cuando habla de una página, quiere decir una plana o dos planas? Y se pueden agregar imágenes como anexo, sin que cuenten en la página de límite?

**Comment by domingomery** [comment]
Hola! 1) una página es una plana, dos planas son dos páginas... 2) no incluir anexos, sólo revisaremos una página, o sea una plana. Saludos. Domingo

**Comment by perojas3** [comment]
Tengo una duda con el Informe. En el enunciado de la parte cuatro dice:
4) Conclusiones: mencionar las conclusiones a las que se llegó.

No entiendo a que se refiere eso. ¿Es lo que aprendi de la tarea? ¿O el resultado de los experimentos?

**Comment by domingomery** [comment]
En las conclusiones de un trabajo típicamente se escribe, para qué sirve lo
que se hizo, si se puede emplear en otros temas, trabajos futuros, qué se
desprende de los resultados obtenidos, etc. En el caso de la tarea se puede
poner si el método desarrollado serviría para otro tipo de fonts, qué
habría que hacer para otras letras, qué mejoras posibles se podrían
implementar, etc. No estoy diciendo que hay que colocar todo esto, sólo
pongo algunos ejemplos para que te sirvan como guía. Obviamente, puedes
incluir otras conclusiones. Saludos. Domingo

**Comment by flobarrios** [comment]
Hola! me queda una pequeña duda con el formato de entrega del código. Si estoy haciéndolo en python, simplemente tengo que decir donde está la función reconocedorSC y usted la ejecuta de forma manual las 100 veces? O se espera un programa por consola que pida el nombre del archivo que contiene a la imagen?

Mi approach hasta ahora es que por la línea de comandos se llama al archivo y se da como argumento el nombre del archivo con la imagen. Se usa así:

```
 python3 reconocedorSC.py S01.npy
```

Esta bien eso? Si no, cual es la forma correcta?

Muchas gracias!

**Comment by chepo92** [comment]
@flobarrios lo dice en el enunciado
> 
> 'Para la tarea se requiere escribir un código en Matlab o Python que tenga la siguiente sintaxis:
> 
> Y = reconocedorSC(X)'

**Comment by flobarrios** [comment]
@chepo92 vi el enunciado! pero creo que está mas pensado en matlab que en python. Mi pregunta era mas para facilitar la corrección.

**Comment by domingomery** [comment]
La forma correcta está relacionada con la primera alternativa: debes decir donde está la función reconocedorSC y yo la ejecuto en un código que llama tu funcion 100 veces… el input de tu función es una matriz X. Saludos. Domingo

**Comment by flobarrios** [comment]
@domingomery perfecto! Última duda, debo subir mi dataset?

**Comment by domingomery** [comment]
Florencia, el enunciado no dice nada del dataset... solo debes entregar lo neceasario para que tu código funcione correctamente. Saludos. Domingo
