### ISSUE TITLE
Explicación PAT02_HuMoments

### ISSUE THREAD

**Issue by asimonv** [domingomery/patrones#11]
Profesor, podría explicar un poco qué es lo que hacen las líneas del case 1?:

https://github.com/domingomery/patrones/blob/8790cef72d0da9c95fb1411dda63b92281e6fcad/clases/Cap02_Extraccion_de_Caracteristicas/matlab/PAT02_HuMoments.m#L15

En verdad mi duda es cómo (en términos de código) se segmenta cada R cuando pregunta qué número es?

**Comment by domingomery** [comment]
Este case lo que hace es segmentar cada uno de los números, esto es asilar los números 1,2,3 y ponerlos en la pantalla, y así mismo se le pregunta al usuario qué número es, esto es lo que se conoce cómo supervisión (un experto humano dice a qué clase pertenece carácter). La segmentación se hace con la función [bwlabel](https://la.mathworks.com/help/images/ref/bwlabel.html)

la ejecución de esta parte del código se muestra en el [video de la clase](https://www.youtube.com/watch?v=J8nhfgUTXXs) en el minuto 41:15

**Comment by domingomery** [comment]
paso esta conversación al foro de la [clase 03](https://github.com/domingomery/patrones/issues/8). En el futuro, les recomiendo hacer las preguntas en los foros de las clases correspondientes para dejar todos los comentarios ordenados por clase. Gracias

**Comment by asimonv** [comment]
> paso esta conversación al foro de la [clase 03](https://github.com/domingomery/patrones/issues/8). En el futuro, les recomiendo hacer las preguntas en los foros de las clases correspondientes para dejar todos los comentarios ordenados por clase. Gracias

Lo iba a hacer ahí, pero como era algo más de código, cree una nueva issue. Gracias profe!
