### ISSUE TITLE
Proyecto

### ISSUE THREAD

**Issue by GboreB** [domingomery/patrones#12]
Profesor, buenas tardes. 
Una consulta sobre el proyecto y las tareas: de a cuantos alumnos son los grupos a formar?

saludos,
GBB

**Comment by domingomery** [comment]
el proyecto en grupos de 4 personas (como siempre digo 4 es 4, no es ni 3 ni 5, ni otro número:)

las tareas son individuales

Saludos

**Comment by GboreB** [comment]
gracias!

saludos,

**Comment by fprebolledo** [comment]
hola, respecto a las fotos, cómo haremos si no podemos salir?

**Comment by domingomery** [comment]
> hola, respecto a las fotos, cómo haremos si no podemos salir?

había pensado cambiar el tema del proyecto con datos que podamos bajar de la red y asi no tener que salir de la casa... les aviso pronto

**Comment by joseluishaddad** [comment]
Hola Profesor,
una consulta respecto al proyecto. 
Quisiera saber si la idea es reconocer gente con mascarilla en imágenes del tipo retrato, o en imágenes por ejemplo de una cámara de seguridad donde se ve mucha gente transitando, o en cualquier tipo de imágenes donde haya gente con mascarillas.

Me gustaría agregar que me pareció muy interesante la idea del proyecto!
Gracias de antemano.

**Comment by domingomery** [comment]
será una cara por foto, cara centrada centrada y frontal... es decir el proyecto se tratará de "face recognition" y no de "face detection". Saludos

Domingo

**Comment by joseluishaddad** [comment]
¿es necesario que todas las fotos tengan la misma expresión facial? (cara con sonrisa, seria, etc.)

**Comment by domingomery** [comment]
el reconocimiento facial es mas efectivo con caras que tengan una expresion neutral... para el proyecto habria que tratar de conseguir este tipo de caras, o que la expresion facial sea lo mas neutral posible... como las que usé en el ejemplo de Mañalich. Saludos. Domingo

Saludos

**Comment by vichoeq** [comment]
Hola, tengo un par de dudas sobre las fotos que saquemos para la base de datos:

* importa el color de la mascarilla? 
* puede una misma persona tener distintos peinados? O tener una foto con, por ejemplo, un gorro?

Para saber que tan creativos nos podemos poner con las fotos.

Gracias

**Comment by domingomery** [comment]
van respuestas:

- no importa color de la mascarilla
- pueden tener distintos peinados y gorros, lo importante es la cara

saludos

**Comment by fprebolledo** [comment]
Hola, cuando dice que debemos usar 5 estrategias distintas en cada set, se deben entregar estas 5? como 5 scripts diferentes para cada set? o entregamos el que mejor dio resultados?

**Comment by domingomery** [comment]
es suficiente poner la mejor.. saludos

**Comment by beayancan** [comment]
Hola profesor.

Quería preguntarle sobre las fechas de las entregas del proyecto, ya que en google classroom aparecen para el día 23 y 25 de junio.

Saludos.

**Comment by domingomery** [comment]
mañana lo aviso en clases, luego de eso actualizo los calendarios. Saludos

**Comment by domingomery** [comment]
He implementado en Python el algoritmo SRC de reconocimiento facial usando Sparse Represetations (con la libreria sklearn):

https://github.com/domingomery/patrones/tree/master/clases/Cap04_Clasificacion/python/SRC

SRC en Matlab ya estaba implementado en:

https://github.com/domingomery/patrones/blob/master/clases/Cap04_Clasificacion/matlab/PAT04_SRC_faces.m

**Comment by domingomery** [comment]
He agregado todas las presentaciones de avance [aqui](https://github.com/domingomery/patrones/tree/master/proyecto/PresentacionesAvance).

Buen trabajo! Felicitaciones!!!

**Comment by fprebolledo** [comment]
Hola profesor, tengo una consulta respecto al punto 3 de la presentación final:
![imagen](https://user-images.githubusercontent.com/26394880/86399562-764a5580-bc75-11ea-92e7-876fdcb7b27b.png)
El método se refiere a los exprimentos que se realizaron verdad?, caract sacadas, clasificadores usados, etc ? , y por otro lado, en la demo, se requiere que se presente el software funcionando, que es lo que se debe mostrar ?  un print del accuracy ? print de la matriz de confusión ?  o que se inserte una imagen y este diga a que clase pertenece? y ver si es correcto ? . Gracias

**Comment by domingomery** [comment]
Asi es Francisca, pero sientanse muy libres en como presentan los
resultados y el metodo propuesto (por metodo se entiende la estrageia
empleada), solo les quiero pedir que hagan un gran esfuerzo por poder
transmitir las ideas, los detalles de tal forma que se entienda bien lo que
hicieron. Las matrices de confusion son suficientes, y que puedan mostrar
las imagenes en que se equivoca. Saludos.

**Comment by domingomery** [comment]
El calendario de presentaciones oficial esta en el Google Calendar del curso:

Calendario de presentaciones: [Google Calendar](https://domingomery.ing.puc.cl/teaching/patrones/)

**Comment by fprebolledo** [comment]
Cuanto debe durar aprox la presentación final?

**Comment by domingomery** [comment]
alrededor de 20 minutos la presentacion y otros 20 las preguntas... saludos

**Comment by domingomery** [comment]
**LINK PARA ZOOM**

Para la presentacion usaremos el mismo zoom de las clases:

[https://notredame.zoom.us/my/patrones](https://notredame.zoom.us/my/patrones)

Meeting ID: 386 155 8778

Por favor ser puntuales.

**Comment by fprebolledo** [comment]
Hola, donde se entrega el ppt final?

**Comment by domingomery** [comment]
me la envían por mail después de la presentación. saludos
