### ISSUE TITLE
Inscripción grupo proyecto

### ISSUE THREAD

**Issue by caespinoza5** [domingomery/patrones#15]
Hola profesor,

Mi duda es si la inscripción del grupo la realiza solo un miembro del grupo o todos. Además, quería consultar si la conformación de grupos sigue teniendo plazo máximo hasta hoy a las 18.30.

¡Gracias!

**Comment by domingomery** [comment]
nos ponemos de acuerdo mañana.... voy a dar una semana mas para esto

Saludos
