### ISSUE TITLE
Personas 'Famosas' escogidas en la base de dato del proyecto

### ISSUE THREAD

**Issue by domingomery** [domingomery/patrones#16]
**PARA EVITAR DUPLICIDAD DE PERSONAS DE LA BASE DE DATOS**

Si algún grupo escoge una persona famosa (por ejemplo Sebastián Piñera), por favor reportar en este foro que esta persona ya ha sido ‘enrolada’, de esta forma cada grupo antes de escoger a una persona debe verificar en el foro si esta persona ya ha sido tomada.

Pueden incluir en la base de datos a personas no famosas (con previo consentimiento), pueden ser familiares, amistades, ustedes mismos. Estas personas no deben notificarlas en este foro.

**Comment by bastianfeliz** [comment]
Siguiendo la tendencia de personajes, yo usaré a:
* El ministro **Gonzalo Blumel** 
* La ministra **María Zaldivar**
* El ministro **Hernán Larraín**

**Comment by vndiaz1** [comment]
Siguiendo con personas del país, yo usaré a:

- **Sebastián Piñera**
- **Joaquín Lavín** (alcalde de Las Condes)
- **Arturo Zúñiga** (subsecretario de redes asistenciales)

**Comment by ranieto** [comment]
- Jair Bolsonaro

**Comment by PamelaRomero** [comment]
* **Paula Daza** (Subsecretaria de Salud Pública)

**Comment by caespinoza5** [comment]
Usaremos a:
- **Emmanuel Macron** (Presidente de Francia)
- **Xi Jinping** (Presidente de la república de China)
- **Martín Vizcarra** (Presidente de Perú)
- **Shinzo Abe** (Primer ministro de Japón)
- **Felipe VI de España** (Rey de españa)
- **Moon Jae In** (Presidente de Korea del sur)

**Comment by YeseniaHelem** [comment]
- Shinzō Abe (ministro de Japón)

**Comment by helemysm** [comment]
- **Jorge Larrañaga** (Ministro del Interior Uruguay)

- **Arturo Murillo** (Ministro Bolivia)

**Comment by pdpino** [comment]
* **Rodolfo Carter** (Alcalde de La Florida)

**Comment by PamelaRomero** [comment]
* **Tsai Ing-wen** - Presidenta de la República de China (Taiwán)

**Comment by AngelBiskupovic** [comment]
Nosotros usaremos a:

- Felipe Alessandri (Alcalde de Santiago)
- Izkia Siches (Presidenta del colegio médico)
- Alejandro Giammattei (Presidente de Guatemala)
-Zuzana Čaputová (Presidenta de Eslovaquia)

**Comment by aeperalta** [comment]
- Pamela Jiles (diputada)

**Comment by jpchaconr** [comment]
- **Raúl Figueroa** (Ministro de educación)

**Comment by dtmaltrain** [comment]
- **Jose Manuel Palacios** (Alcalde de La Reina)

- **Evelyn Matthei** (Alcaldesa de Providencia)

**Comment by ranieto** [comment]
- Lucas Palacios (Ministro de Economía)

**Comment by beayancan** [comment]
* Nicolás Maduro (Presidente de Venezuela)
* Markus Söder (Primer Ministro de Baviera)

**Comment by Juan-AAS** [comment]
Cathy Barriga (Alcaldesa de Maipú)

**Comment by VicenteVicente** [comment]
* Ignacio Sanchez (Rector PUC)
* Felipe Guevara (Intendente RM)
* José Fernández (Intendente Magallanes)

**Comment by GboreB** [comment]
Katherine Martonell, Subsecretaria prevención del delito

**Comment by diegoheg** [comment]
- K?D (Dj americano)

**Comment by diegoheg** [comment]
Jared Polis (Gobernador de Colorado, EEUU)

**Comment by hagarces** [comment]
Johnny Carrasco (Alcalde de Pudahuel)
Paula Labra (Seremi de salud)

**Comment by diegoheg** [comment]
Eric Garcetti (Político Estadounidense)

**Comment by michimalonko** [comment]
Domingo Mery (El mismisimo)

**Comment by AngelBiskupovic** [comment]
- Giuseppe Conte (Primer ministro de Italia)

**Comment by valeria-adasme** [comment]
- Ben Affleck

**Comment by valeria-adasme** [comment]
- Sandra Oh

**Comment by caespinoza5** [comment]
- Prayut chan-o-cha (Primer ministro de tailandia)

**Comment by BFFV** [comment]
- Nelson Teich (ex-Ministro de Salud de Brasil)

**Comment by BFFV** [comment]
- Macarena Santelices (Ministra de la Mujer en Chile)

**Comment by cjmunoz4** [comment]
- Pedro Sánchez (Presidente del Gobierno de España)

**Comment by maguzman5** [comment]
- Alejandro García (Seremi Salud Coquimbo)

- Marcelo Pereira (Alcalde Coquimbo)
