### ISSUE TITLE
Código Fuente de "Face Alignment with OpenCV and Python"

### ISSUE THREAD

**Issue by bastianfeliz** [domingomery/patrones#17]
Como algunos se habrán dado cuenta, es tedioso obtener el código para alinear las caras desde la página (te piden tu mail, confirmación, etc). Así que aquí les dejo el link del código fuente en drive ♥. 

https://drive.google.com/file/d/1bf3oyXh6g-6IZNRjplbarCo6J3wvcf5N/view?usp=sharing

Saludos

**Comment by joseluishaddad** [comment]
Estoy teniendo un problema al intentar correrlo en el que me dice `cannot connect to X server`.
Alguien más tuvo ese problema y pudo solucionarlo?
