### ISSUE TITLE
Alineacion caras proyecto

### ISSUE THREAD

**Issue by fprebolledo** [domingomery/patrones#18]
Alguien más tiene el problema de que el código dado en clases no detecta las caras con mascarillas? como lo están haciendo?

**Comment by ewaugh2** [comment]
A mi me pasó con algunas caras, para solucionarlo saqué la foto un poco distinta. Lo otro que ayuda es bajar un poco la mascarilla para que se vean bien los ojos.

**Comment by ewaugh2** [comment]
@domingomery me pasa que guardo las fotos alineadas con extensión jpg pero los archivos son formato jpeg. Debo transformar las fotos? O basta con tener la extensión correcta?
