### ISSUE TITLE
Proyecto

### ISSUE THREAD

**Issue by domingomery** [domingomery/patrones#6]
Estimado/as,

antes de este lunes 27/05 a las 23:59hrs deben inscribir el los integrantes del Grupo del Proyecto del curso.

IMPORTANTE: El grupo debe ser de 4 personas (no más de 4 ni menos de 4 personas). Las personas que no se inscriban con este formulario serán inscritas por el profesor de manera aleatoria en nuevos grupos.

Para esto cada grupo deben llenar este formulario.

https://es.surveymonkey.com/r/DSTLRP5

*** UN FORMULARIO POR GRUPO ***

Saludos

Domingo

**Comment by nfurrejola** [comment]
Hola! 

Somos un grupo de 3 estudiantes buscando a una cuarta persona para concretar el grupo de trabajo. Somos muy responsables y no tenemos preferencia respecto al lenguaje que manejen mejor para el curso (MATLAB o Python). Les dejo mi correo cualquier cosa: nfurrejola@uc.cl

Saludos!

**Comment by icontrerasn** [comment]
Hola,
También estamos buscando un cuarto integrante para el proyecto. iocontreras@uc.cl

**Comment by alainrochette** [comment]
Alguien sabe para cuando es la próxima entrega? (La de explicar las opciones de métodos por usar)

**Comment by baarratia** [comment]
Era para hoy al término del módulo de clases (12:50)

**Comment by Taeval** [comment]
Cómo hay que enviar lo de los métodos que vamos a usar?

**Comment by domingomery** [comment]
como dije el martes en clases, hoy hasta las 12:50hrs cada grupo debe mandarme un mail diciendo que es lo que van a hacer para resolver el problema (un mail por grupo). Saludos. Domingo

**Comment by domingomery** [comment]
Para medir el desempeño de la solución se usará además del FMR y el FNMR el valor 'd-prime' (muy parecido al discriminante Fisher) calculado de la siguiente manera:

dprime = abs(m_gen-m_imp)/sqrt((v_gen+v_imp)/2)

donde

- m_gen y m_imp son los valores medios de la distancia calculada en el set de genuinos y en el set de impostores respectivamente

- v_gen y v_imp son las varianzas de la distancia calculada en el set de genuinos y en el set de impostores respectivamente

Entre más alto sea el valor de d-prime mayor será la separación entre las distribuciones de genuinos e impostores. Ver definición [aquí](https://en.wikipedia.org/wiki/Sensitivity_index)

**Comment by Taeval** [comment]
Alguien logró instalar Dlib en Windows 10?

**Comment by AlfonsoIgnacioV** [comment]
Hola!
Tenemos una duda con respecto a 'd-prime'. Específicamente, no entendemos si corresponde a una separación que nos dice qué tan bueno es nuestro **extractor** (lbp, gabor, hog, etc)  (porque finalmente está usando los vectores que obtiene el extractor y está midiendo qué tan similares son los vectores), o si en realidad está midiendo qué tan buena es la **clasificación** (en ese caso, ¿dónde entraría el clasificador para efectos de la multiplicación de x_a y x_b transpuesta, siendo x_a y x_b las características?). 

Dicho de otra manera, ¿se usa antes o después de clasificar?

No sé si se entiende 
Muchas gracias
Saludos

**Comment by AlfonsoIgnacioV** [comment]
Por lo que entendemos ahora, no hay nunca un clasificador, ¿es así?

**Comment by domingomery** [comment]
Ignacio, por revisar el último mail enviado, y los apuntes de clases sobre
'metric learning'... Este no es un problema de clasificación como los que
han hecho en las tareas con clases específicas, deben decir si dos fotos
son de una misma persona o no. Por favor revisar esta PPT:

https://github.com/domingomery/patrones/blob/master/clases/Cap05_Evaluacion/presentations/PAT05_Genuine_Impostor.pptx


Saludos. Domingo

**Comment by weierstrass1** [comment]
Disculpe profe, es que el set de datos ya viene dividido en training y test, se puede juntar todo el set de datos para aplicar cross validation u otra técnica para probar rendimiento?

**Comment by domingomery** [comment]
Hola! como resultados adicional pueden juntar todo y hacer un
cross-validation, pero lo que tienen que reportar todos los grupos es un
hold-out con los subsets de training y testing especificados en las
carpetas, asi todos los grupos tienen el mismo protocolo experimental y se
pueden hacer comparaciones. Saludos. Domingo

**Comment by perojas3** [comment]
Tengo las siguientes dudas:
1.- En la presentación PAT05_Genuine_Impostor.pptx, nunca se menciona textualmente el nombre dprime ¿Cual de las cosas que se mencionan alli es el dprime?
2.- (esta es para todos) En el diagrama, ¿Alguno sabe como obtener los datos del diagrama de una red neuronal MLP en sklearn? Es que no encuentro la forma

**Comment by domingomery** [comment]
para la respuesta 1 por favor ver lo que escribí más arriba hace 1 semana sobre la definición de dprime (ver ecuación y link de wikipedia) y darse cuenta que dprime = d’ (d prima en castellano), en la ppt dprime es d’ y coincide con esta definición. Saludos. Domingo

**Comment by perojas3** [comment]
¿Cuando doodle con los horarios?
